### ISSUE TITLE
how are the .pts files generated?

### ISSUE THREAD

**Issue by joanne1112** [IsaacGuan/PointNet-Plane-Detection#2]
Hi, Isaac!
Thanks for sharing the code. I am also studying Pointnet but I am new to the 3D point cloud.
Could you please tell me how to get the .pts files from the .ply files?

Thanks before!
Joanne

**Comment by IsaacGuan** [comment]
Hi Joanne,
I think you could also use the [plyfile](https://github.com/dranjan/python-plyfile), the tool I proposed for making the HDF5 file from PLY file. As PTS is a unordered list of 3D coordinates with no headers or trailers, the only thing we need to do is to read the points from the PLY file and write them in to a list. 
Concretely, you could take this as a reference: https://isaacguan.github.io/2018/05/04/Prepare-Your-Own-Data-for-PointNet/#PLY-Data

**Comment by joanne1112** [comment]
Got it! Thanks a lot!
