### ISSUE TITLE
can't find tf_util.py and provider.py

### ISSUE THREAD

**Issue by phyllisnping** [IsaacGuan/PointNet-Plane-Detection#3]
Hi Isaac!

Thank you for your idea!
I tried to train your network but cannot find tf_util.py and provider.py file in your project.
Shall I write them or where can I find them?

Thank you!

**Comment by joanne1112** [comment]
They are included in the Pointnet code by Charles.

**Comment by IsaacGuan** [comment]
Hi,
Joanne is right, this repository can be seen as a plugin to PointNet. If you want to run the code, please download my forked repository of PointNet: https://github.com/IsaacGuan/pointnet

**Comment by Nhunguts** [comment]
Hi everyone, I used the tf_util.py and provider.py from Charles. However I got another error:

Traceback (most recent call last):
  File "D:/PointNet-Plane-Detection-master/train.py", line 334, in <module>
    train()
  File "D:/PointNet-Plane-Detection-master/train.py", line 312, in train
    train_one_epoch(epoch)
  File "D:/PointNet-Plane-Detection-master/train.py", line 178, in train_one_epoch
    cur_data, cur_seg = provider.loadDataFile_with_seg(train_filename)
  File "D:\PointNet-Plane-Detection-master\provider.py", line 108, in loadDataFile_with_seg
    return load_h5_data_label_seg(filename)
  File "D:\PointNet-Plane-Detection-master\provider.py", line 102, in load_h5_data_label_seg
    label = f['label'][:]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Python37\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'label' doesn't exist)"

Process finished with exit code 1

Please help me with this. Thank you.

**Comment by Lizhinwafu** [comment]
> Hi everyone, I used the tf_util.py and provider.py from Charles. However I got another error:
> 
> Traceback (most recent call last):
> File "D:/PointNet-Plane-Detection-master/train.py", line 334, in 
> train()
> File "D:/PointNet-Plane-Detection-master/train.py", line 312, in train
> train_one_epoch(epoch)
> File "D:/PointNet-Plane-Detection-master/train.py", line 178, in train_one_epoch
> cur_data, cur_seg = provider.loadDataFile_with_seg(train_filename)
> File "D:\PointNet-Plane-Detection-master\provider.py", line 108, in loadDataFile_with_seg
> return load_h5_data_label_seg(filename)
> File "D:\PointNet-Plane-Detection-master\provider.py", line 102, in load_h5_data_label_seg
> label = f['label'][:]
> File "h5py_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> File "h5py_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> File "C:\Python37\lib\site-packages\h5py_hl\group.py", line 264, in **getitem**
> oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
> File "h5py_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> File "h5py_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> File "h5py\h5o.pyx", line 190, in h5py.h5o.open
> KeyError: "Unable to open object (object 'label' doesn't exist)"
> 
> Process finished with exit code 1
> 
> Please help me with this. Thank you.

Me too, have you solved it？

**Comment by Nhunguts** [comment]
Hi @Lizhinwafu, let try to change a function called "load_h5_data_label_seg(h5_filename)" in the file "provider.py" as follow:

def load_h5_data_label_seg(h5_filename):
    f = h5py.File(h5_filename)
    data = f['data'][:]
    #label = f['label'][:]
    seg = f['pid'][:]
    #return (data, label, seg)
    return (data, seg) 

because the h5 file of Isaac doesn't contain "label". 
However, the method of Issac didn't work with my data, it segmented all points to one class. 
Hope this help.

**Comment by piyushsingh2k7** [comment]
Hi I have downloaded and used the tf_util.py and provider.py from Charles. However, I got another error:


>>> Training for the epoch 1/100 ...
Loading train file /home/vrmslab/Downloads/PointNet-Plane-Detection-master/./data/hdf5_data/data_training.h5
Traceback (most recent call last):
  File "/home/vrmslab/Downloads/PointNet-Plane-Detection-master/train.py", line 333, in <module>
    train()
  File "/home/vrmslab/Downloads/PointNet-Plane-Detection-master/train.py", line 312, in train
    train_one_epoch(epoch)
  File "/home/vrmslab/Downloads/PointNet-Plane-Detection-master/train.py", line 178, in train_one_epoch
    cur_data, cur_seg = provider.loadDataFile_with_seg(train_filename)
AttributeError: 'module' object has no attribute 'loadDataFile_with_seg'

can anyone suggest how to remove this error ?

**Comment by piyushsingh2k7** [comment]
> Hi @Lizhinwafu, let try to change a function called "load_h5_data_label_seg(h5_filename)" in the file "provider.py" as follow:
> 
> def load_h5_data_label_seg(h5_filename): f = h5py.File(h5_filename) data = f['data'][:] #label = f['label'][:] seg = f['pid'][:] #return (data, label, seg) return (data, seg)
> 
> because the h5 file of Isaac doesn't contain "label". However, the method of Issac didn't work with my data, it segmented all points to one class. Hope this help.

i have used your suggestion but after running it gives an error i.e

and got this output error after running it

Training for the epoch 1/100 ...
Loading train file /home/vrmslab/Downloads/PointNet-Plane-Detection-master/./data/hdf5_data/data_training.h5
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273024 thread 1 bound to OS proc set 1
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273073 thread 2 bound to OS proc set 2
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273074 thread 3 bound to OS proc set 3
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273075 thread 4 bound to OS proc set 4
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273076 thread 5 bound to OS proc set 5
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273077 thread 6 bound to OS proc set 6
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273078 thread 7 bound to OS proc set 7
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273079 thread 8 bound to OS proc set 8
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273080 thread 9 bound to OS proc set 9
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273081 thread 10 bound to OS proc set 10
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273083 thread 12 bound to OS proc set 12
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273082 thread 11 bound to OS proc set 11
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273084 thread 13 bound to OS proc set 13
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273085 thread 14 bound to OS proc set 14
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273086 thread 15 bound to OS proc set 15
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273087 thread 16 bound to OS proc set 0
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273025 thread 17 bound to OS proc set 1
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273088 thread 18 bound to OS proc set 2
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273089 thread 19 bound to OS proc set 3
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273090 thread 20 bound to OS proc set 4
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273091 thread 21 bound to OS proc set 5
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273092 thread 22 bound to OS proc set 6
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273093 thread 23 bound to OS proc set 7
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273094 thread 24 bound to OS proc set 8
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273095 thread 25 bound to OS proc set 9
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273096 thread 26 bound to OS proc set 10
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273097 thread 27 bound to OS proc set 11
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273098 thread 28 bound to OS proc set 12
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273099 thread 29 bound to OS proc set 13
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273100 thread 30 bound to OS proc set 14
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273101 thread 31 bound to OS proc set 15
OMP: Info #254: KMP_AFFINITY: pid 272970 tid 273102 thread 32 bound to OS proc set 0
Training Total Mean_loss: 0.344301
Training Seg Mean_loss: 0.344301
Training Seg Accuracy: 0.455200

<<< Testing on the test dataset ...
Loading test file /home/vrmslab/Downloads/PointNet-Plane-Detection-master/./data/hdf5_data/data_testing.h5
Traceback (most recent call last):
File "/home/vrmslab/Downloads/PointNet-Plane-Detection-master/train.py", line 333, in
train()
File "/home/vrmslab/Downloads/PointNet-Plane-Detection-master/train.py", line 315, in train
eval_one_epoch(epoch)
File "/home/vrmslab/Downloads/PointNet-Plane-Detection-master/train.py", line 253, in eval_one_epoch
cur_data, cur_seg = provider.load_h5_data_label_seg(train_filename)
NameError: global name 'train_filename' is not defined



please help me in doing it correctly  ...
