### ISSUE TITLE
Segmentation Visualization

### ISSUE THREAD

**Issue by joanne1112** [IsaacGuan/PointNet-Plane-Detection#4]
Hi, Isaac,

Could you please explain how can we visualize the point cloud after segmentation prediction?
Thank you!

Joanne

**Comment by IsaacGuan** [comment]
Hi Joanne,
There are some geometry processing tools that could load those OBJ output file, e.g., the [MeshLab](http://www.meshlab.net/).

**Comment by joanne1112** [comment]
Thank you so much!
